
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                    : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "pl"
title                    : "Samouczek Programisty"
title_separator          : "-"
name                     : "Marcin Pietraszek"
description              : "Cześć! Jestem Marcin :) Pracuję jako programista od 2007 roku. Na blogu chcę podzielić się z Tobą moją pasją do programowania."
url                      : "https://www.samouczekprogramisty.pl"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "SamouczekProgramisty/samouczekprogramisty.github.io"
teaser                   : /assets/images/default_post_image.gif
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : "samouczekprogramisty" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment."
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               : "SamouczekProgramisty"
  app_id                 :
  publisher              :
youtube:
  url                    : "https://www.youtube.com/channel/UCisPQ5nxB6yw3SfJPFWKTEg"
github:
  username               : "SamouczekProgramisty"
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-68536783-1"
    anonymize_ip         : true # true, false (default)


# Site Author
author:
  name             : "Marcin Pietraszek"
  avatar           : "/assets/images/marcin_pietraszek.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Cześć! Jestem Marcin :) Pracuję jako programista od 2007 roku. Na blogu chcę podzielić się z Tobą moją pasją do programowania."
  location         :
  email            :
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "kbl"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "marcinpietraszek"
  pinterest        :
  soundcloud       :
  stackoverflow    : "957130/marcin-pietraszek"
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - scripts
  - podzial-artykulow.txt
  - samouczkowy_slownik.txt
  - _metaassets
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/
timezone: "Europe/Warsaw" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  sort_reverse: true
  extension: 'html'


# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-toc
  - jekyll-gist

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /kategorie/
tag_archive:
  type: liquid
  path: /tagi/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      header:
        overlay_filter: 0.5


collections:
    courses:
        output: true
    sections:
        output: true


doclinks:
    java:
        io:
            BufferedReader: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/BufferedReader.html
            DataInputStream: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/DataInputStream.html
            DataOutputStream: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/DataOutputStream.html
            Externalizable: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/Externalizable.html
            File: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/File.html
            FileInputStream: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/FileInputStream.html
            FileOutputStream: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/FileOutputStream.html
            FileReader: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/FileReader.html
            FileWriter: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/FileWriter.html
            NotSerializableException: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/NotSerializableException.html
            ObjectInputStream: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/ObjectInputStream.html
            ObjectOutputStream: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/ObjectOutputStream.html
            PrintWriter: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/PrintWriter.html
            Serializable: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/Serializable.html
        lang:
            AssertionError: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/AssertionError.html
            AutoCloseable: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/AutoCloseable.html 
            Double: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Double.html
            Enum: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Enum.html
            Float: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Float.html
            FunctionalInterface: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/FunctionalInterface.html
            Integer: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Integer.html
            Long: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Long.html
            Math: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Math.html
            Object: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Object.html
            Override: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Override.html
            String: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/String.html
            StringBuffer: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/StringBuffer.html
            StringBuilder: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/StringBuilder.html
            SuppressWarnings: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/SuppressWarnings.html
            System: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/System.html
            ThreadLocal: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/ThreadLocal.html
            annotation:
                Target: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/annotation/Target.html
        nio:
            file:
                AccessMode: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/AccessMode.html
        time:
            LocalDateTime: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/time/LocalDateTime.html
        util:
            Collections: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Collections.html
            Comparator: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Comparator.html
            Formatter: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Formatter.html
            HashMap: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/HashMap.html
            List: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/List.html
            Locale: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Locale.html
            Map: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Map.html
            Objects: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Objects.html
            Scanner: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Scanner.html
            Set: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Set.html
            StringJoiner: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/StringJoiner.html
            function:
                IntSupplier: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/function/IntSupplier.html
                Supplier: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/function/Supplier.html
                package: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/function/package-summary.html
            regex:
                Pattern: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/regex/Pattern.html
                Matcher: https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/regex/Matcher.html
    javax:
        annotation:
            PostConstruct: https://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html
        servlet:
            Filter: http://docs.oracle.com/javaee/7/api/javax/servlet/Filter.html
            FilterChain: http://docs.oracle.com/javaee/7/api/javax/servlet/FilterChain.html
            GenericServlet: https://docs.oracle.com/javaee/7/api/javax/servlet/GenericServlet.html
            Servlet: https://docs.oracle.com/javaee/7/api/javax/servlet/Servlet.html
            ServletContext: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html
            ServletContextAttributeListener: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextAttributeListener.html
            ServletContextListener: http://docs.oracle.com/javaee/7/api/javax/servlet/ServletContextListener.html
            ServletOutputStream: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletOutputStream.html
            ServletRequest: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html
            ServletRequestAttributeListener: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestAttributeListener.html
            ServletRequestListener: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequestListener.html
            ServletResponse: https://docs.oracle.com/javaee/7/api/javax/servlet/ServletResponse.html
            annotation:
                WebFilter: http://docs.oracle.com/javaee/7/api/javax/servlet/annotation/WebFilter.html
                WebListener: https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/WebListener.html
            http:
                Cookie: https://docs.oracle.com/javaee/7/api/javax/servlet/http/Cookie.html
                HttpServlet: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServlet.html
                HttpServletRequest: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html
                HttpServletResponse: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html
                HttpSession: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html
                HttpSessionAttributeListener: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionAttributeListener.html
                HttpSessionListener: https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSessionListener.html
        validation:
            constraints:
                NotNull: http://docs.oracle.com/javaee/7/api/javax/validation/constraints/NotNull.html
                Valid: http://docs.oracle.com/javaee/7/api/javax/validation/Valid.html
    specs:
        http11: http://www.ietf.org/rfc/rfc2616.txt
        jar: https://docs.oracle.com/en/java/javase/12/docs/specs/jar/jar.html
        jee7: http://www.oracle.com/technetwork/java/javaee/tech/index.html
        jls: https://docs.oracle.com/javase/specs/jls/se12/html/
        serialization: https://docs.oracle.com/en/java/javase/12/docs/specs/serialization/
        servlet: https://jcp.org/en/jsr/detail?id=340
    tools:
        jar: https://docs.oracle.com/en/java/javase/12/tools/jar.html
        java: https://docs.oracle.com/en/java/javase/12/tools/java.html
        javac: https://docs.oracle.com/en/java/javase/12/tools/javac.html
